spring.application.name=api-cobrancas

spring.datasource.url=jdbc:postgresql://localhost:5432/db_cobrancas
spring.datasource.username=postgres
spring.datasource.password=master

spring.jpa.hibernate.ddl-auto=update

